"""Report builder: StepRecord[] → Markdown / PDF.

Deterministic — no LLM calls.
"""

from __future__ import annotations

import logging
import textwrap
from pathlib import Path

from deriv_verifier.schemas import StepRecord, VerificationReport

logger = logging.getLogger(__name__)

_STATUS_EMOJI = {
    "valid": "✅",
    "weak": "⚠️",
    "invalid": "❌",
    "unchecked": "⬜",
}

_DECISION_LABEL = {
    "pending": "pending",
    "accepted": "accepted by user",
    "rejected": "rejected by user",
    "refined": "refined by user",
}


# ---------------------------------------------------------------------------
# Markdown report
# ---------------------------------------------------------------------------


def build_markdown(report: VerificationReport) -> str:
    """Render *report* as a Markdown string."""
    lines: list[str] = []

    # Header
    lines += [
        "# Derivation Verification Report",
        "",
        f"**Session ID:** `{report.session_id}`  ",
        f"**Source file:** `{report.source_file}`  ",
        f"**Model:** `{report.model_used}`  ",
        "",
        "## Summary",
        "",
        f"| Steps | Valid | Weak | Invalid | Unchecked |",
        f"|-------|-------|------|---------|-----------|",
        f"| {report.total_steps} | {report.valid_count} | {report.weak_count}"
        f" | {report.invalid_count} | {report.unchecked_count} |",
        "",
    ]

    if report.summary:
        lines += [report.summary, ""]

    if report.has_critical_issues:
        lines += ["> **⚠ WARNING:** This derivation contains INVALID steps. Review required.", ""]

    # Per-step details
    lines += ["## Step-by-Step Verification", ""]

    for step in report.steps:
        lines += _render_step_md(step)

    # Footer
    lines += [
        "---",
        "",
        f"*Generated by Derivation Verifier. Session: `{report.session_id}`*",
    ]
    return "\n".join(lines)


def _render_step_md(step: StepRecord) -> list[str]:
    icon = _STATUS_EMOJI.get(step.status, "⬜")
    lines = [
        f"### Step {step.id} — {icon} `{step.status.upper()}`",
        "",
        f"**Claim:** {step.claim}",
        "",
        "**LaTeX:**",
        "```latex",
        step.raw_latex,
        "```",
        "",
        f"**Reason:** {step.reason or '(none)'}",
        f"**Confidence:** {step.confidence:.0%}",
        f"**CoVe rounds:** {step.cove_rounds}",
        f"**User decision:** {_DECISION_LABEL.get(step.user_decision, step.user_decision)}",
        "",
    ]

    if step.missing_assumptions:
        lines += ["**Missing assumptions:**", ""]
        for a in step.missing_assumptions:
            lines.append(f"- {a}")
        lines.append("")

    if step.hand_wave_flags:
        lines += ["**Hand-wave flags:**", ""]
        for f in step.hand_wave_flags:
            lines.append(f"- {f}")
        lines.append("")

    if step.notation_issues:
        lines += ["**Notation issues:**", ""]
        for n in step.notation_issues:
            lines.append(f"- {n}")
        lines.append("")

    if step.suggested_lemma:
        lines += [f"**Suggested lemma:** {step.suggested_lemma}", ""]

    if step.suggested_rewrite:
        lines += [
            "**Suggested rewrite:**",
            "```latex",
            step.suggested_rewrite,
            "```",
            "",
        ]

    if step.tools_called:
        lines += [f"**Tools called:** {', '.join(step.tools_called)}", ""]

    lines.append("---")
    lines.append("")
    return lines


def write_markdown(report: VerificationReport, path: str | Path) -> Path:
    """Render and write the Markdown report to *path*."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    md = build_markdown(report)
    path.write_text(md, encoding="utf-8")
    logger.info("Markdown report written to %s.", path)
    return path


# ---------------------------------------------------------------------------
# PDF report (optional — requires reportlab)
# ---------------------------------------------------------------------------


def write_pdf(report: VerificationReport, path: str | Path) -> Path:
    """Render the report as a PDF using reportlab.

    Raises ``ImportError`` if reportlab is not installed.
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            Paragraph,
            SimpleDocTemplate,
            Spacer,
            Table,
            TableStyle,
        )
    except ImportError as exc:
        raise ImportError(
            "reportlab is required for PDF export. Install it: pip install reportlab"
        ) from exc

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(str(path), pagesize=A4)
    styles = getSampleStyleSheet()
    story: list[object] = []

    # Title
    story.append(Paragraph("Derivation Verification Report", styles["Title"]))
    story.append(Spacer(1, 0.3 * cm))

    # Meta
    meta = [
        f"Session: {report.session_id}",
        f"Source: {report.source_file}",
        f"Model: {report.model_used}",
    ]
    for line in meta:
        story.append(Paragraph(line, styles["Normal"]))
    story.append(Spacer(1, 0.5 * cm))

    # Summary table
    summary_data = [
        ["Steps", "Valid", "Weak", "Invalid", "Unchecked"],
        [
            str(report.total_steps),
            str(report.valid_count),
            str(report.weak_count),
            str(report.invalid_count),
            str(report.unchecked_count),
        ],
    ]
    table = Table(summary_data, hAlign="LEFT")
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 0.5 * cm))

    # Per-step sections
    for step in report.steps:
        icon = {"valid": "[VALID]", "weak": "[WEAK]", "invalid": "[INVALID]"}.get(
            step.status, "[UNCHECKED]"
        )
        story.append(
            Paragraph(f"Step {step.id} — {icon}", styles["Heading2"])
        )
        story.append(Paragraph(f"<b>Claim:</b> {step.claim}", styles["Normal"]))
        story.append(Paragraph(f"<b>Reason:</b> {step.reason or '(none)'}", styles["Normal"]))
        story.append(
            Paragraph(f"<b>Confidence:</b> {step.confidence:.0%}", styles["Normal"])
        )
        if step.suggested_lemma:
            story.append(
                Paragraph(f"<b>Suggested lemma:</b> {step.suggested_lemma}", styles["Normal"])
            )
        story.append(Spacer(1, 0.3 * cm))

    doc.build(story)
    logger.info("PDF report written to %s.", path)
    return path
